name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
  attestations: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cli/gh-extension-precompile@v2
        with:
          go_version_file: go.mod
          go_build_options: -ldflags=-X=github.com/advanced-security/gh-ghas-audit/v2/cmd.buildVersion=${{ github.ref_name }}
          generate_attestations: true
 
